#!/usr/bin/env python3
# SPDX-License-Identifier: 0BSD
"""Research report for official Transvoxel-equivalence without copying MIT tables."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Iterable, List, Set

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "validation" / "official_equivalence_research_report.json"
MD = ROOT / "validation" / "official_equivalence_research_report.md"


def read_json(path: Path) -> Dict[str, object]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def transform_case(case: int, kind: str) -> int:
    bits = [(case >> i) & 1 for i in range(9)]
    out = [0] * 9
    for y in range(3):
        for x in range(3):
            if kind == "identity":
                nx, ny = x, y
            elif kind == "rot90":
                nx, ny = 2 - y, x
            elif kind == "rot180":
                nx, ny = 2 - x, 2 - y
            elif kind == "rot270":
                nx, ny = y, 2 - x
            elif kind == "mirror_x":
                nx, ny = 2 - x, y
            elif kind == "mirror_y":
                nx, ny = x, 2 - y
            elif kind == "transpose":
                nx, ny = y, x
            elif kind == "anti_transpose":
                nx, ny = 2 - y, 2 - x
            else:
                raise ValueError(kind)
            out[nx + ny * 3] = bits[x + y * 3]
    return sum((b << i) for i, b in enumerate(out))


def orbit_count(transforms: Iterable[str], complement: bool) -> int:
    transforms = list(transforms)
    classes: Dict[int, List[int]] = {}
    for case in range(512):
        orbit: Set[int] = set()
        for t in transforms:
            tc = transform_case(case, t)
            orbit.add(tc)
            if complement:
                orbit.add(tc ^ 511)
        classes.setdefault(min(orbit), []).append(case)
    return len(classes)


def main() -> int:
    tv_path = ROOT / "generated" / "transvoxel_tables.json"
    tv = json.loads(tv_path.read_text(encoding="utf-8")) if tv_path.exists() else {}
    transition = tv.get("transition", {})
    current_cases = int(transition.get("case_count", 0))
    current_classes = int(transition.get("class_count", 0))
    c4 = ["identity", "rot90", "rot180", "rot270"]
    d4 = ["identity", "rot90", "rot180", "rot270", "mirror_x", "mirror_y", "transpose", "anti_transpose"]
    symmetry_counts = {
        "C4_rotations_only": orbit_count(c4, False),
        "C4_rotations_plus_complement": orbit_count(c4, True),
        "D4_rotations_reflections_only": orbit_count(d4, False),
        "D4_rotations_reflections_plus_complement": orbit_count(d4, True),
    }
    expected_official_classes = 73
    naive_groups_matching_73 = [k for k, v in symmetry_counts.items() if v == expected_official_classes]
    topology_report = read_json(ROOT / "validation" / "topology_signature_report.json")
    topology_summaries = topology_report.get("class_summaries", {}) if isinstance(topology_report, dict) else {}
    status = "RESEARCH_PASS_OFFICIAL_EQUIVALENCE_NOT_PROVEN"
    official_equivalence = "NOT_PROVEN"
    report = {
        "schema": "boqsc.transvoxel.official_equivalence_research.v1",
        "status": status,
        "official_transvoxel_equivalence_proof": official_equivalence,
        "safe_research_boundary": {
            "allowed": [
                "public structural facts from papers/docs",
                "independent symmetry/orbit derivation",
                "topology signatures generated by this project",
                "API-shape comparison without numeric table ingestion",
            ],
            "not_allowed": [
                "copying official MIT table arrays",
                "using official table data as golden output",
                "editing generated values to match official numeric arrays",
            ],
        },
        "official_public_facts_used": {
            "transition_cases": 512,
            "transition_equivalence_classes": expected_official_classes,
            "lod_ratio": "2:1 adjacent blocks",
            "transition_face_owner": "low-resolution block renders transition face toward high-resolution neighbor",
        },
        "current_project_facts": {
            "transition_cases": current_cases,
            "current_transition_classes": current_classes,
            "compression": tv.get("compression", "unknown"),
        },
        "naive_3x3_symmetry_orbit_counts": symmetry_counts,
        "naive_groups_matching_official_73": naive_groups_matching_73,
        "topology_signature_analysis": {
            "status": topology_report.get("status", "NOT_RUN") if isinstance(topology_report, dict) else "NOT_RUN",
            "matches_official_73_count": topology_report.get("matches_official_73_count", False) if isinstance(topology_report, dict) else False,
            "closest_count_to_official_target": topology_report.get("closest_count_to_official_target", {}) if isinstance(topology_report, dict) else {},
            "class_counts": {k: v.get("class_count") for k, v in topology_summaries.items()} if isinstance(topology_summaries, dict) else {},
        },
        "interpretation": [
            "The project covers 512 transition cases.",
            "The current export is direct one-class-per-case and not official 73-class compressed.",
            "Naive 3x3 grid symmetry/complement grouping does not reproduce the official 73 classes.",
            "Therefore official 73-class equivalence requires a deeper independent topology derivation, not a trivial bit-pattern grouping and not copied table data.",
        ],
        "next_steps": [
            "derive transition topology signatures from paper diagrams/text without table arrays",
            "define our reference sign/orientation convention formally",
            "derive candidate canonical classes from topology signatures",
            "prove 512 case to class mapping by documented transforms",
            "compare boundary/topology signatures instead of byte/table values",
        ],
    }
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    lines = [
        "# Official-Equivalence Research Report",
        "",
        f"Status: **{status}**",
        "",
        f"Official equivalence proof: **{official_equivalence}**",
        "",
        "## Current facts",
        "",
        f"- Current transition cases: `{current_cases}`",
        f"- Current transition classes: `{current_classes}`",
        f"- Official transition classes: `{expected_official_classes}`",
        "",
        "## Naive 3x3 symmetry counts",
        "",
    ]
    for k, v in symmetry_counts.items():
        lines.append(f"- `{k}`: `{v}`")
    lines += [
        "",
        "## Topology signature analysis",
        "",
    ]
    if isinstance(topology_summaries, dict) and topology_summaries:
        for k, v in topology_summaries.items():
            if isinstance(v, dict):
                lines.append(f"- `{k}`: `{v.get('class_count')}` classes")
        closest = topology_report.get("closest_count_to_official_target", {}) if isinstance(topology_report, dict) else {}
        lines.append(f"- closest-to-73: `{closest.get('name')}` with `{closest.get('class_count')}` classes")
    else:
        lines.append("- topology signature analysis was not available when this report ran")
    lines += [
        "",
        "None of the naive groups equals 73. The generated topology-signature groups also do not prove official 73-class equivalence. This means official equivalence research must derive or reproduce the official topology-class relation from the publication, not from simple bit-pattern symmetry.",
        "",
    ]
    MD.write_text("\n".join(lines), encoding="utf-8")
    print("official equivalence research:", status)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
