#!/usr/bin/env python3
# SPDX-License-Identifier: 0BSD
"""Generate an M25-backed replacement for Godot Voxel's table translation unit."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
M26_DIR = ROOT / "research" / "official_topology" / "m26"
M25_CPP = (
    ROOT
    / "research"
    / "official_topology"
    / "m25"
    / "generated"
    / "Transvoxel.cpp"
)
GENERATED_DIR = M26_DIR / "generated"
OUTPUT = GENERATED_DIR / "transvoxel_tables.cpp"
REPORT = GENERATED_DIR / "godot_voxel_replacement_layout.json"


ACCESSORS = r"""
inline unsigned char get_regular_cell_class(unsigned int i) {
	ZN_ASSERT(i < 256);
	return regularCellClass[i];
}

inline const RegularCellData &get_regular_cell_data(unsigned int i) {
	ZN_ASSERT(i < 16);
	return regularCellData[i];
}

inline unsigned short get_regular_vertex_data(
		unsigned int i, unsigned int j) {
	ZN_ASSERT(i < 256);
	ZN_ASSERT(j < 12);
	return regularVertexData[i][j];
}

inline unsigned char get_transition_cell_class(unsigned int i) {
	ZN_ASSERT(i < 512);
	return transitionCellClass[i];
}

inline const TransitionCellData &get_transition_cell_data(unsigned int i) {
	ZN_ASSERT(i < 56);
	return transitionCellData[i];
}

inline unsigned char get_transition_corner_data(unsigned int i) {
	ZN_ASSERT(i < 13);
	return transitionCornerData[i];
}

inline unsigned short get_transition_vertex_data(
		unsigned int i, unsigned int j) {
	ZN_ASSERT(i < 512);
	ZN_ASSERT(j < 12);
	return transitionVertexData[i][j];
}
"""


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    body = M25_CPP.read_text(encoding="utf-8")
    text = "\n".join([
        "// SPDX-License-Identifier: MIT",
        "// Copyright (c) 2009 Eric Lengyel",
        "// Exact compatibility data; see LICENSES/MIT.txt.",
        "// Generated by the 0BSD M26 build tool from MIT-licensed M25 data.",
        '#include "../../util/errors.h"',
        "",
        "namespace zylann::voxel::transvoxel::tables {",
        "",
        body.rstrip(),
        "",
        ACCESSORS.strip(),
        "",
        "} // namespace zylann::voxel::transvoxel::tables",
        "",
    ])
    OUTPUT.write_text(text, encoding="utf-8")
    required = [
        "namespace zylann::voxel::transvoxel::tables",
        "struct RegularCellData",
        "struct TransitionCellData",
        "get_regular_cell_class",
        "get_regular_cell_data",
        "get_regular_vertex_data",
        "get_transition_cell_class",
        "get_transition_cell_data",
        "get_transition_corner_data",
        "get_transition_vertex_data",
    ]
    missing = [token for token in required if token not in text]
    report = {
        "schema": "boqsc.transvoxel.m26.godot_voxel_layout.v1",
        "status": (
            "PASS_M26_GODOT_VOXEL_REPLACEMENT_LAYOUT"
            if not missing
            else "FAIL_M26_GODOT_VOXEL_REPLACEMENT_LAYOUT"
        ),
        "source": str(M25_CPP.relative_to(ROOT)).replace("\\", "/"),
        "output": str(OUTPUT.relative_to(ROOT)).replace("\\", "/"),
        "source_sha256": sha256(M25_CPP),
        "output_sha256": sha256(OUTPUT),
        "missing_contract_tokens": missing,
        "report_license": "0BSD",
        "aggregate_only": True,
        "output_data_license": "MIT",
        "output_license_file": "LICENSES/MIT.txt",
    }
    REPORT.write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print("M26 Godot Voxel layout:", report["status"])
    return 0 if not missing else 1


if __name__ == "__main__":
    raise SystemExit(main())
